[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "example_package_robystar"
version = "0.0.1"
authors = [
  { name="Example Author", email="roberto.starnini@gisweb.it" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/robystar/sampleproject.git"
"Bug Tracker" = "https://github.com/robystar/sampleproject.git/issues"